language: node_js
node_js:
  - "10.15.2"
script:
  - echo "Deploying"

before_script:
  - npm install -g firebase-tools
  - npm install -g @vue/cli@latest
  - npm install

script:
  - npm run build

after_success:  
  - firebase deploy --token "1/B-la_ujEUpsNX_EZEmotiqqz_ANoPz8merlayyE-tkPMOvRX-eV1DHuhxsPsDfJO"

